# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
before_install:
  - tlmgr install index
brew_packages:
  - udunits
apt_packages:
  - libudunits2-dev
addons:
       apt:
         update: true
         sources:
           - sourceline: 'ppa:opencpu/imagemagick'
         packages:
           - libmagick++-dev
