---
title: "Dealing with missing values in time series"
author: "Fred Hasselman"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Dealing with missing values in time series}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
	fig.align = "center",
	fig.height = 6,
	fig.width = 7,
	message = FALSE,
	warning = FALSE,
	collapse = FALSE,
	comment = ">",
	width = 500
)
library(invctr)
library(casnet)
library(plyr)
library(tidyverse)
```

## ["Much ado about nothing"](http://www.math.smith.edu/~nhorton/muchado.pdf)


https://cran.r-project.org/web/views/MissingData.html 


https://addi.ehu.es/bitstream/handle/10810/19052/TFM-MALUnaiGarciarena.pdf?sequence=1&isAllowed=y 
https://gking.harvard.edu/amelia 

https://cran.r-project.org/web/packages/HotDeckImputation/HotDeckImputation.pdf 


### Data

```{r}
# # Load data from OSF https://osf.io/tcnpd/
# require(osfr)
# manyAnalystsESM <- rio::import(osfr::osf_download(osfr::osf_retrieve_file("tcnpd") , overwrite = TRUE)$local_path)

# Or use the internal data
data(manyAnalystsESM)

# We want to use these variables
# Note: the infix function '%ci%' is from package 'invctr'
vars <- c("angry"%ci%manyAnalystsESM,"ruminate"%ci%manyAnalystsESM,"hours"%ci%manyAnalystsESM)
df_vars    <-  manyAnalystsESM[,vars]

# Create different variable types, we can use these to check imputation "accuracy"
set.seed(54321)
df_vars$zscore <- zscore <- rnorm(NROW(df_vars))
df_vars$zscore[is.na(df_vars$angry)] <- NA
df_vars$unif_discrete <- unif_discrete  <- round(runif(NROW(df_vars),min = 0,max = 6))
df_vars$unif_discrete[c(10:15,74:78,111,120)] <- NA
df_vars$cat_unordered <- cat_unordered  <- factor(round(runif(NROW(df_vars),min = 1,max = 7)))
df_vars$cat_unordered[c(10:15,74:78,111,120)] <- NA
df_vars$cat_ordered <- cat_ordered <- ordered(round(runif(NROW(df_vars),min = 1,max = 20)))
df_vars$cat_ordered[is.na(df_vars$angry)] <- NA
```

Function `statsNA()` can produce some hellful stats on `NA`s

```{r}
require(imputeTS)
require(mice)

imputeTS::statsNA(df_vars$angry)

imputeTS::statsNA(df_vars$unif_discrete)

```


### Kalman filter

```{r}

out.kalman <- t(laply(1:NCOL(df_vars), function(c){
  y <- as.numeric(as.numeric_discrete(x = df_vars[,c], keepNA = TRUE))
  cbind(imputeTS::na.kalman(y, model =  "auto.arima"))
  }))
colnames(out.kalman) <- colnames(df_vars)
```

### Multiple imputation: auto-select method

The function `mice()` will try to select a method based on variable type
```{r}
library(mice)
# auto choice by mice algorithm
# mice schooses pmm: 
imp.mice <- mice(df_vars, printFlag = FALSE)
out.auto <- complete(imp.mice)

```


### Multiple imputation: classification & regression trees


```{r}
out.auto <- complete(imp.mice)

# RF and CART return (identical) discrete numbers
imp.cart  <- mice(df_vars, meth = 'cart', printFlag = FALSE)
out.cart  <- complete(imp.cart)

# imp.rf  <- mice(df_vars, meth = 'rf')
# out.rf  <- complete(imp.cart)

```

### Compare imputation methods

We can check "truth" values for the created valiables. 

```{r, fig.height=3}
truth <- list(df_vars$angry, df_vars$ruminate, df_vars$hours, zscore, unif_discrete, cat_unordered, cat_ordered)

for(c in 1:NCOL(df_vars)){
  
print(colnames(df_vars)[c])
  
  withNA  <- as.numeric_discrete(df_vars[,c], keepNA = TRUE)
  Truth   <- as.numeric_discrete(truth[[c]], keepNA = TRUE)
  
plotNA.imputations(x.withNA = withNA, 
                     x.withImputations = as.numeric_discrete(out.cart[,c]), 
                     x.withTruth =Truth,
                     main="regression trees",
                     ylab = colnames(df_vars)[c])

plotNA.imputations(x.withNA = withNA, 
                   x.withImputations = as.numeric_discrete(out.auto[,c]), 
                   x.withTruth = Truth,
                   main = paste("auto:",imp.mice$method)[c],
                   ylab = colnames(df_vars)[c])

plotNA.imputations(x.withNA = withNA, 
                   x.withImputations = out.kalman[,c], 
                   x.withTruth = Truth,
                   main = "kalman filter",
                   ylab = colnames(df_vars)[c])

}

```





